version: "3.9"
services:
  metamodel:
    platform: linux/amd64
    build: ./src/metamodel
    ports:
      - "5003:5003"
  graph-based:
    platform: linux/amd64
    build: ./src/graph-based
    ports:
      - "5004:5004"
  t5-headline:
    platform: linux/amd64
    build: ./src/t5-headline
    ports:
      - "5005:5005"
  t5-article:
    platform: linux/amd64
    build: ./src/t5-article
    ports:
      - "5006:5006"
  sumbasic:
    platform: linux/amd64
    build: ./src/sumbasic
    ports:
      - "5007:5007"
  hybrid-long:
    platform: linux/amd64
    build: ./src/hybrid-long
    ports:
      - "5008:5008"